apiVersion: v1
kind: Service
metadata:
  name: nh-svc
    # labels:
    #app: nhfe
spec:
  type: NodePort
  ports:
  - port: 80
    #nodePort: 30001
    #protocol: TCP
    targetPort: http-web-svc
  selector:
    app: nhfe
